# Generated by Django 3.2.6 on 2021-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='その他', max_length=10, verbose_name='カテゴリー'),
        ),
    ]
