# Generated by Django 3.2.6 on 2021-08-18 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0006_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans1',
            field=models.CharField(default='選択肢１', max_length=30, verbose_name='回答１'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans1_num',
            field=models.IntegerField(default=0, verbose_name='回答１投票数'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans2',
            field=models.CharField(default='選択肢２', max_length=30, verbose_name='回答２'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans2_num',
            field=models.IntegerField(default=0, verbose_name='回答２投票数'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans3',
            field=models.CharField(max_length=30, null=True, verbose_name='回答３'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans3_num',
            field=models.IntegerField(default=0, verbose_name='回答３投票数'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans4',
            field=models.CharField(max_length=30, null=True, verbose_name='回答４'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans4_num',
            field=models.IntegerField(default=0, verbose_name='回答４投票数'),
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('q', 'user')},
        ),
        migrations.RemoveField(
            model_name='good',
            name='ans',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
