# Generated by Django 3.2.6 on 2021-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20210819_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='num',
            field=models.IntegerField(default=0, verbose_name='問題番号'),
        ),
    ]
