# Generated by Django 3.2.6 on 2021-08-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_good_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='good',
            unique_together=set(),
        ),
    ]
