# Generated by Django 3.2.6 on 2021-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_good_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='回答３'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='回答４'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='質問'),
        ),
    ]
