# Generated by Django 3.2.6 on 2021-09-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20210827_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='num',
        ),
    ]
