# Generated by Django 3.2.6 on 2021-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_remove_good_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='num',
            field=models.IntegerField(default=0, verbose_name='問題番号'),
        ),
    ]
